@startuml
interface Target {
    + request() : void
}

class Adaptee {
    + specificRequest() : void
}

class Adapter implements Target {
    - adaptee : Adaptee
    + request() : void
}

Target <|.. Adapter
Adapter --> Adaptee
@enduml
