@startuml
interface Subject {
    + request() : void
}

class RealSubject implements Subject {
}

class Proxy implements Subject {
    - realSubject : RealSubject
    + request() : void
}

Subject <|-- RealSubject
Subject <|-- Proxy
Proxy --> RealSubject
@enduml